//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPasal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTransaction
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Remark { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Description { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
