//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectPasal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTransaction
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Descrition { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
